config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/login'
  root 'static_pages#home'
  get '/about', to: "static_pages#about"
  get '/contact', to: "static_pages#contact"
  get '/news', to: "static_pages#news"
  get '/sign_up', to: "users#new"
  get 'login', to: "sessions#new"
  post '/login',to: "sessions#create"
  get '/logout', to: "sessions#destroy"
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	VALID_EMAIL_REGEX = /\A[\w\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :name, :email, presence: true
	# validates :name, length: {minimum: 2, maximum: 150}
	validates :email, length: {maximum: 255, message: "Email toi da 255 ki tu"}
	validates :email, format: {with: VALID_EMAIL_REGEX}, uniqueness: true
	has_secure_password 
	validates :password, presence: true, length: {maximum: 72}, confirmation: true
	# validates :check_length_name, if: ->{name.present?}

	# def check_length_name
	# 	if name.size > 150
	# 		errors.add :name, "Ten qua dai"
	# 	end
	# end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include StaticPagesHelper
	include ApplicationHelper

	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	#tim user theo email
  	@user = User.find_by email: params[:session][:email].downcase
  	#neu ton tai user thi check password cua user
  	

  	if @user.present? && @user.authenticate(params[:session][:password])
  		flash[:success] = "Hello #{@user.name}"
  		login_user @user
  		redirect_to @user #user_path(@user)
  	else
  		#neu ko ton tai thi tra ve loi
  		flash.now[:danger] = "Error !!!!"
  		render :new
  	end
  end

  def destroy
  	session.delete(:user_id)
  	@current_user = nil
  	flash[:success] = "Goobye!!"
  	redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	include StaticPagesHelper
  def home
  end

  def show
  	@user = User.find_by id: params[:id]
  end

  def help
  end

  def login
  end

  def about
  end

  def contact
  end

  def news
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :is_login?, only: [:show] #trc khi vao action show thi ktra login chua
	def show
		@user = User.find_by id: params[:id]
	end

	def new 
		@user = User.new
	end

	def create
		@user = User.new user_params
		if @user.save
			#xu ly thanh cong
			flash[:success] = "Create account success !!!"
			redirect_to @user #show ra thông tin user vừa tạo
		else
			#xu ly that bai
			flash.now[:danger] = "Create account fail !!!"
			render :new
		end
	end

	private 
	def user_params
		params.require(:user).permit :name, :email, :password, :password_confirmation #chỉ chấp nhận 4 thuộc tính này
	end

	

end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_user
		@current_user ||=  User.find_by id: session[:user_id]
	end

	def login_user user
		session[:user_id] = user.id
	end

	def is_login?
		#neu co thi tra ve doi tuong
		return if current_user 
		#neu ko thi thong bao va chuyen ve trang login
			flash[:danger] = "You need login"
			redirect_to login_path
		end	
	end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
	def full_title page_title =""
		base_title = "Ruby on Rails Tutorial Sample App"
		page_title.empty? ? base_title : "#{page_title} | #{base_title}"  
	end

	def base_url url =""
		base_url = "http://127.0.0.1:3000";
		url.empty? ? base_url : "#{base_url}/#{url}"
	end
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/layouts/_content.html.erb
<div class="content">
	<div class="container">
		<% flash.each do |type_message, message| %>
		<div class="alert alert-<%= type_message %>"><%= message %></div>
		<% end %>
    	<%= yield %>
	</div>
</div>

app/views/layouts/_error_messages.html.erb
<% if @user.errors.any? %>
	<p class="alert alert-danger">Form contains <%= @user.errors.size %></p>
	<p class="alert alert-success" >Form contains <%= pluralize(@user.errors.count, "error") %></p>
	<ul>
		<% @user.errors.full_messages.each do |mgs| %>
		<li style="color: red"><%= mgs %></li>
		<% end %>
	</ul>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
	<div class="container">
		<div class="row">
			<div class="col-xs-8">
				<span class="contact">Liên hệ: <span class="gmail">levietkhanh99@gmail.com</span></span>
			</div>
			<div class="col-xs-4">
				<a href="/about" class="link_footer">About</a>
				<a href="/contact" class="link_footer">Contact</a>
				<a href="/news" class="link_footer">News</a>
				<span><%= link_to "News", news_path %></span>
				<span><%= link_to "News", news_url %></span>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_header.html.erb
<div class="header">
	<header class="navbar navbar-fixed-top navbar-inverse">
		<div class="container">
			<%= link_to "sample_app", base_url, id: "logo" %>
			<nav>
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "Home" , base_url("static_pages/home") %></li>
					<li><%= link_to "Help" , base_url("static_pages/help") %></li>
					<% if current_user %>
						<li><%= link_to "Logout", logout_path, method: :delete %></li>
					<% else %>
						<li><%= link_to "Login", login_path %></li>
					<% end %>
				</ul>
			</nav>
		</div>
	</header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/content" %>
    <%= render "layouts/footer" %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide :title, "About" %>
<h1>About page</h1>

app/views/static_pages/contact.html.erb
<% provide :title, "Contact" %>
<h1>Contact page</h1>

app/views/static_pages/help.html.erb
<% provide :title, 'Help' %>
<h1>Help</h1>
<p>
	Get help on the Ruby on Rails Tutorial at the
	<a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
	book</a>
</p>

app/views/static_pages/home.html.erb
<% provide :title, 'Home' %>
<h1>Sample App</h1>
<p>
	This is the home page for the
	<a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
	sample application.
</p>

app/views/static_pages/login.html.erb
<% provide :title, 'Login' %>
<div class="login">
	<h1>Login</h1>
	<form>
	    <label for="username">Username</label> <br>
	    <input type="text" class="username" id="username" name="username" placeholder="Username">
	  
	    <label for="password">Password</label> <br>
	    <input type="password" class="password" id="password" name="password" placeholder="Password">
	  
	  <input type="submit" class="submit_login" name="btn_login" value="Login">
	</form>
</div>

app/views/static_pages/news.html.erb
<% provide :title, "News" %>
<h1>News page</h1>

app/views/static_pages/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

app/views/users/new.html.erb
<% provide :title, "Sign up" %>
<h1>Sign up</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for @user, url: users_path do |f| %>

		<%= render "layouts/error_messages" %>

		<%= f.label :name %>
		<%= f.text_field :name %>

		<%= f.label :email %>
		<%= f.email_field :email %>

		<%= f.label :password %>
		<%= f.password_field :password %>

		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>

		<%= f.submit "Create my account", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<h1>
<%= gravatar_for @user %>
<%= @user.name %>
</h1>